blank_issues_enabled: false
contact_links:
  - name: "📖 Documentation"
    url: "https://github.com/AbdelrahmanDwedar/mig#readme"
    about: "Read the official documentation to learn how to use Mig."
